### ISSUE TITLE
参照正文SSH在线安装出现问题，固件为 stone 2.7

### ISSUE THREAD

**Issue by sky540** [user1121114685/koolproxyR#11]
/tmp/KoolProxyR_install.sh: source: line 5: can't open '/koolshare/scripts/base.sh'

**Comment by user1121114685** [comment]
sorry 目前只支持 koolshare LEDE X64

其他平台请移植规则处理文件。

**Comment by user1121114685** [comment]
在KP的基础上 将kpr的规则覆盖原来kp的规则即可
kpr规则处理文件
`https://github.com/user1121114685/koolproxyR/blob/master/koolproxyR/scripts/KoolProxyR_rule_update.sh`

**Comment by sky540** [comment]
> 在KP的基础上 将kpr的规则覆盖原来kp的规则即可
> kpr规则处理文件
> `https://github.com/user1121114685/koolproxyR/blob/master/koolproxyR/scripts/KoolProxyR_rule_update.sh`

谢谢解答，不过kp已经被我卸载了，好像安装不了

**Comment by user1121114685** [comment]
> > 在KP的基础上 将kpr的规则覆盖原来kp的规则即可
> > kpr规则处理文件
> > `https://github.com/user1121114685/koolproxyR/blob/master/koolproxyR/scripts/KoolProxyR_rule_update.sh`
> 
> 谢谢解答，不过kp已经被我卸载了，好像安装不了。期待以后支持更多平台

只需要在安装的kp上移植这个脚本，就行了。稍微懂点shell的人都能胜任。
