### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by aetaf** [user1121114685/koolproxyR#14]
OpenWrt SNAPSHOT, r1363-16d7e45
 -----------------------------------------------------
root@OpenWrt:~# wget -O /tmp/KoolProxyR_install.sh https://raw.githubusercontent.com/user1121114685/koolproxyR/master/KoolProxyR_install.sh && chmod 777 /tmp/KoolProxyR_install.sh
 && sh /tmp/KoolProxyR_install.sh
--2019-05-08 13:59:16--  https://raw.githubusercontent.com/user1121114685/koolproxyR/master/KoolProxyR_install.sh
Resolving raw.githubusercontent.com... 151.101.108.133
Connecting to raw.githubusercontent.com|151.101.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4841 (4.7K) [text/plain]
Saving to: '/tmp/KoolProxyR_install.sh'

/tmp/KoolProxyR_install.sh                   100%[=============================================================================================>]   4.73K  --.-KB/s    in 0s

2019-05-08 13:59:17 (36.7 MB/s) - '/tmp/KoolProxyR_install.sh' saved [4841/4841]

/tmp/KoolProxyR_install.sh: source: line 5: can't open '/koolshare/scripts/base.sh': No such file or directory

**Comment by user1121114685** [comment]
暂时不支持koolshare lede x64以外的平台安装。
