### ISSUE TITLE
过滤规则影响电视盒子版本的优酷客户端登录

### ISSUE THREAD

**Issue by ericwang2006** [user1121114685/koolproxyR#15]
只启用了KPR主规则和视频规则, 开启了HTTPS全局过滤, 证书已经导入, 看其他视频客户端正常(比如爱奇艺), 只有电视盒子版本的优酷客户端不能登录, 但是先关闭广告过滤, 登录后再开启广告过滤, 是可以过滤优酷应用的广告的.

**Comment by user1121114685** [comment]
好的感谢反馈

**Comment by ericwang2006** [comment]
补充一下, 这个测试结果是在 2.0.3版本下测试的,  在:2.0.4版本下测试是既不能会员登录, 也不能播放视频,  优酷客户端是最新的 CIBN酷喵影视6.9.3.1

**Comment by user1121114685** [comment]
> 补充一下, 这个测试结果是在 2.0.3版本下测试的, 在:2.0.4版本下测试是既不能会员登录, 也不能播放视频, 优酷客户端是最新的 CIBN酷喵影视6.9.3.1

感谢反馈

**Comment by user1121114685** [comment]
> 补充一下, 这个测试结果是在 2.0.3版本下测试的, 在:2.0.4版本下测试是既不能会员登录, 也不能播放视频, 优酷客户端是最新的 CIBN酷喵影视6.9.3.1

你可以再更新规则试试。

**Comment by ericwang2006** [comment]
测试最新版本已经没问题了，非常感谢！
