### ISSUE TITLE
bilibili APP 图片无法加载

### ISSUE THREAD

**Issue by avsba001** [user1121114685/koolproxyR#24]
**你所使用的设备：例如 s10+
我正在使用：

**是否启用http/https模式**
https是否启用:启用

**证书是否安装正确**
未root，安装的用户证书

已经@@@@将bilibili.com加入白名单

**Comment by user1121114685** [comment]
其实这样还会有很多app会提示无网，请知悉

**Comment by avsba001** [comment]
是不是有些cdn站被拦截了，导致的检测无网，只能时间积累解决这个问题了

**Comment by user1121114685** [comment]
并不是，是因为安卓7.0以上谷歌改变了证书的信任策略，必须内置.0根证书到 `/system/etc/security/cacerts          /system/etc/security/cacerts_google`才可以被信任。
