### ISSUE TITLE
小米应用商店无法下载app~

### ISSUE THREAD

**Issue by miantiao1025** [user1121114685/koolproxyR#26]
全局用的http模式~并没有用https模式~ 甚至在访问控制里添加手机不过滤也不行- -~
全家都用的小米手机都不能安装。

**Comment by user1121114685** [comment]
请在附加功能中，开启调试模式--ad 然后重新操作小米手机进行安装测试，并将日志全部粘贴进来。感谢

**Comment by miantiao1025** [comment]
【2019年05月15日 21:57:03】: 关闭koolproxyR主进程...
【2019年05月15日 21:57:03】: kpr   debug-ad模式启动
koolproxy v3.8.4
listen port=3000
log level=2
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/AdGuard_DNS.txt
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:192.168.1.130:41464 transfer to 111.202.0.73:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v2
::ffff:192.168.1.248:42630 transfer to 123.125.102.106:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v3
::ffff:192.168.1.130:41478 transfer to 111.202.0.73:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v2
::ffff:192.168.1.193:41243 transfer to 123.125.102.106:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v3
::ffff:192.168.1.193:41243 transfer to 123.125.102.106:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v3
::ffff:192.168.1.193:41243 transfer to 123.125.102.106:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v3
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.193:41243 transfer to 123.125.102.106:80 request block. line=52977 url=http://data.mistat.xiaomi.com/mistats/v3
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.130:40918 transfer to 60.217.251.87:80 request block. line=116 url=http://b0.market.xiaomi.com/download/AppStore/0f9e759fcbf7a492262c23ef5941900e241429b9a
::ffff:192.168.1.130:42314 transfer to 47.101.29.206:80 request block. line=53039 url=http://api.tw06.xlmc.sec.miui.com/api/configure/get
::ffff:192.168.1.130:41814 transfer to 47.95.231.197:80 request block. line=116 url=http://b0.market.xiaomi.com/download/AppStore/0f9e759fcbf7a492262c23ef5941900e241429b9a/70f5f6b4859705eaaaa5bd8300126c8a
::ffff:192.168.1.130:42314 transfer to 47.101.29.206:80 request block. line=53039 url=http://api.tw06.xlmc.sec.miui.com/api/configure/get
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.130:47490 transfer to 123.125.102.98:80 request block. line=123 url=http://api.ad.xiaomi.com/appstore/uploadLogSDK
::ffff:192.168.1.193:37336 transfer to

**Comment by user1121114685** [comment]
1.这应该不是小米手机，而是小米电视的，另外只需要更新规则便可以使用了。
2.你下载的 好看视频  
3.对设备进行不过滤仍然无法下载这是从未出现过的，建议关闭kpr并重启lede。然后再开启kpr
