### ISSUE TITLE
关闭插件，然后重启路由，然后打开，更新规则，但是还是不能更新app。我确实用的小米9测试的

### ISSUE THREAD

**Issue by miantiao1025** [user1121114685/koolproxyR#27]
【2019年05月15日 23:57:28】: 关闭koolproxyR主进程...
【2019年05月15日 23:57:28】: kpr   debug-ad模式启动
koolproxy v3.8.4
failed: Operation timed out.
Connecting to easylist-downloads.adblockplus.org|2a01:4f8:c0c:2d11::2|:443... listen port=3000
log level=2
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/AdGuard_DNS.txt
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:192.168.1.130:47990 transfer to 47.101.29.206:80 request block. line=53039 url=http://api.tw06.xlmc.sec.miui.com/api/configure/get
::ffff:192.168.1.130:46600 transfer to 60.217.251.87:80 request block. line=116 url=http://b0.market.xiaomi.com/download/AppStore/0970d4e4071b5f62c0d4399664d1ce6aadf406642
::ffff:192.168.1.130:47990 transfer to 47.101.29.206:80 request block. line=53039 url=http://api.tw06.xlmc.sec.miui.com/api/configure/get
::ffff:192.168.1.130failed: Operation timed out.
Connecting to easylist-downloads.adblockplus.org|2a01:4f8:120:724c::2|:443...

**Comment by user1121114685** [comment]
你可以现在测试测试。因为你的规则在测试时并没有更新。所以现在测试是更新之后的。如果还是有问题我直接推送一个新的版本。

**Comment by miantiao1025** [comment]
谢谢，早上起来，可以更新app了，万分感谢。
