### ISSUE TITLE
koolshare lede 2.31无法安装，离线和命令都不行

### ISSUE THREAD

**Issue by hujinchaopk** [user1121114685/koolproxyR#29]
离线和命令都不行
![image](https://user-images.githubusercontent.com/17800567/57904813-e8f84600-78a6-11e9-856b-f67ab40ad9c7.png)
![TIM截图20190517131906](https://user-images.githubusercontent.com/17800567/57904820-f01f5400-78a6-11e9-92a9-89e0dfadb358.png)
![TIM截图20190517132012](https://user-images.githubusercontent.com/17800567/57904821-f0b7ea80-78a6-11e9-913b-ee17fd6a0d5d.png)
![TIM截图20190517132033](https://user-images.githubusercontent.com/17800567/57904823-f0b7ea80-78a6-11e9-9bea-92ea658ab946.png)

我在github无法访问的地区，两种方式都不行，新机器，重启过了。

**Comment by user1121114685** [comment]
无法访问github，请手动下载离线安装sh文件传送到指定位置。或者通过方式让GitHub走代理进行安装。
