### ISSUE TITLE
adguard 规则有很多重复条目

### ISSUE THREAD

**Issue by imoldchen** [user1121114685/koolproxyR#3]
例如，打开规则文件搜索 crashlytics 会发现有两处相同的规则，而且上下的其他规则条目也是重复的，希望能处理一下重复条目。

**Comment by user1121114685** [comment]
这是因为没法判断网站是http还是https所以必须都覆盖。http对速度几乎没有影响。请不要担心。如果有办法判断规则网站是否是https规则就不会重复了。
