### ISSUE TITLE
KPR 主规则 开启后，IOS it之家无法刷新文章，关了KPR 主规则就可以了~~

### ISSUE THREAD

**Issue by Se7enMuting** [user1121114685/koolproxyR#30]
**你所使用的设备：例如 电脑 MAC IPHONE 小米MIX IPHONE8**
我正在使用：ipad pro 11

**是否启用http/https模式**
https是否启用:是

**证书是否安装正确**
PC安装到【受信任的根证书发布机构】.
安卓7.0以上将.0根证书复制到【/system/etc/security/cacerts】【/system/etc/security/cacerts_google】.
iphone 在设置---通用----关于手机里面信任证书.
MAC 在 【钥匙串访问】中信任。
是

**是否采取下列措施**
1,重启LEDE
2,重新安装证书

**如果重复以上步骤仍然有问题:**
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

**Comment by user1121114685** [comment]
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

**Comment by a57620887** [comment]
大佬 问下支持原版KP证书吗？

**Comment by user1121114685** [comment]
https://github.com/user1121114685/koolproxyR/issues/30#issuecomment-493835453
支持的，可以直接恢复。请多看看玩不转。

**Comment by Se7enMuting** [comment]
`
【2019年05月21日 21:48:46】: 关闭koolproxyR主进程...
【2019年05月21日 21:48:46】: kpr   debug-ad模式启动
koolproxy v3.8.4
listen port=3000
log level=2
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/fanboy-annoyance.txt
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/yhosts.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:192.168.1.140:60268 transfer to 113.113.73.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60267 transfer to 113.113.73.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60269 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60270 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60271 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60272 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60273 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60274 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60275 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60276 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60277 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60278 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60279 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60280 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60281 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60282 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60283 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60285 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60284 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60286 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60287 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60288 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60290 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60289 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60291 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60292 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60293 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60295 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60296 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60297 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60298 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60299 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60300 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60301 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60302 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60303 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60304 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60305 transfer to `

**Comment by Se7enMuting** [comment]
【2019年05月21日 21:48:46】: 关闭koolproxyR主进程...
【2019年05月21日 21:48:46】: kpr   debug-ad模式启动
koolproxy v3.8.4
listen port=3000
log level=2
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/fanboy-annoyance.txt
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/yhosts.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:192.168.1.140:60268 transfer to 113.113.73.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60267 transfer to 113.113.73.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60269 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60270 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60271 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60272 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60273 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60274 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60275 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60276 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60277 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60278 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60279 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60280 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60281 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60282 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60283 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60285 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60284 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60286 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60287 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [api.ithome.com]
::ffff:192.168.1.140:60288 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-80 [dyn.ithome.com]
::ffff:192.168.1.140:60290 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60289 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60291 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60292 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60293 transfer to 219.151.18.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60295 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60296 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60297 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60298 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60299 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60300 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60301 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60302 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60303 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [dyn.ithome.com]
::ffff:192.168.1.140:60304 transfer to 59.63.229.35:443 request read worker tls_handshake failed:-29312 [api.ithome.com]
::ffff:192.168.1.140:60305 transfer to

**Comment by Se7enMuting** [comment]
上面是更新了KPR 2.1.2，5规则全开，全局不过滤，通过访问控制单独过滤ipad，Http/Https双过滤模式

**Comment by user1121114685** [comment]
@@@@https://api.ithome.com
@@@@https://dyn.ithome.com

请把这2个规则加入自定义中。再测试一下看看是否已经正常。

**Comment by Se7enMuting** [comment]
2.1.3加了这2条规则之后OK了~~
