### ISSUE TITLE
开启后系统进程占用高

### ISSUE THREAD

**Issue by muyuqiyan** [user1121114685/koolproxyR#33]
规则就用了主规则、补充规则和视频规则，kpr版本为最新

贴出一段日志

Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20944]: mark mode=0
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20944]: max fd=131070
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20944]: init adblock engine
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20944]: load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
Sat Jun  1 07:43:59 2019 kern.info kernel: [ 1207.628473] traps: koolproxy[20883] general protection ip:4f242b sp:7ffd23d21b20 error:0
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: koolproxy v3.8.4
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: listen port=3000
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: log level=4
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: thread count=4
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: work path=/koolshare/koolproxyR
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: program path=/koolshare/koolproxyR/koolproxy
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: data path=/koolshare/koolproxyR/data
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: ttl mode=188
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: ttl port=3001
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: mark mode=0
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: max fd=131070
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: init adblock engine
Sat Jun  1 07:43:59 2019 kern.info kernel: [ 1208.139486] traps: koolproxy[20944] general protection ip:4f242b sp:7ffd23d21b20 error:0
Sat Jun  1 07:43:59 2019 daemon.notice koolproxy[20967]: load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by muyuqiyan** [comment]
![4D77E1AD-BF0A-4749-8FD1-688A0972BB3478ffc526428b8cad.png](https://tuku.zhazhaa.xyz/images/2019/06/01/4D77E1AD-BF0A-4749-8FD1-688A0972BB3478ffc526428b8cad.png)

**Comment by user1121114685** [comment]
这看cpu的。如果是即时CPU消耗可以无视。如果一直这样，有问题。当你没过滤广告的时候占用应该接近0

**Comment by muyuqiyan** [comment]
> 这看CPU的。如果是即时CPU消耗可以无视。如果一直这样，有问题。当你没过滤广告的时候占用应该接近0

之前cpu正常  昨天看CPU温度升了十度左右  进去看了下  发现这个占用高 这个日志一直出，之前操作过opkg update  和entware lnmp  安装不成功后就关了

**Comment by user1121114685** [comment]
因为你的kpr一直崩溃，重启，所以导致占用过高。你可以使用调试模式-info 把日志发出来我看看。到底哪里出问题了。

**Comment by muyuqiyan** [comment]
@user1121114685 
【2019年06月01日 15:29:16】: 关闭koolproxyR主进程...
【2019年06月01日 15:29:17】: koolproxyR主进程已关闭...
【2019年06月01日 15:29:17】: kpr   debug-info模式启动
koolproxy v3.8.4
listen port=3000
log level=1
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
【2019年06月01日 15:29:19】: koolproxyR主进程已关闭...

**Comment by user1121114685** [comment]
麻烦将将easylistchina.txt，yhosts.txt,拷贝出来下。我审查一下失败原因.
文件在`/koolshare/koolproxyR/data/rules/`

**Comment by muyuqiyan** [comment]
重新安装了 没有那个了😅

**Comment by user1121114685** [comment]
> 重新安装了 没有那个了😅

我差点以为是重大Bug。

**Comment by user1121114685** [comment]
感谢反馈
