### ISSUE TITLE
淘宝无法支付

### ISSUE THREAD

**Issue by alvis-vis** [user1121114685/koolproxyR#35]
**你所使用的设备：小米MIX2
我正在使用：小米MIX2

**是否启用http/https模式**
https是否启用:是

**证书是否安装正确** 是

淘宝无法支付。

**Comment by user1121114685** [comment]
请提供完整的信息，包括证书是否正确安装到指定位置   

安卓7.0以上将.0根证书复制到【/system/etc/security/cacerts】【/system/etc/security/cacerts_google】.  


和请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。
