### ISSUE TITLE
LOFTER(乐乎) 无法显示登陆框

### ISSUE THREAD

**Issue by zhouqiubin** [user1121114685/koolproxyR#36]
**你所使用的设备：例如 电脑 MAC IPHONE 小米MIX IPHONE8**
我正在使用：电脑

**是否启用http/https模式**
https是否启用:是，随后切换http模式，问题依旧

**证书是否安装正确**
PC安装到【受信任的根证书发布机构】.
安卓7.0以上将.0根证书复制到【/system/etc/security/cacerts】【/system/etc/security/cacerts_google】.
iphone 在设置---通用----关于手机里面信任证书.
MAC 在 【钥匙串访问】中信任。

**是否采取下列措施**
1,重启LEDE
2,重新安装证书

**如果重复以上步骤仍然有问题:**
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

【2019年06月03日 20:46:06】: 关闭koolproxyR主进程...
【2019年06月03日 20:46:07】: koolproxyR主进程已关闭...
【2019年06月03日 20:46:07】: kpr   debug-ad模式启动
koolproxy v3.8.4
listen port=3000
log level=2
thread count=4
work path=/tmp
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/fanboy-annoyance.txt
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/yhosts.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:192.168.50.200:7882 transfer to 59.111.239.60:80 request super direct. line=50 url=http://www.lofter.com/login?urschecked=true
::ffff:192.168.50.200:7901 transfer to 59.111.160.209:80 request super direct. line=50 url=http://passport.www.lofter.com/webzj/v1.0.1/pub/index_dl2_new.html?cd=%2F%2Fl.bst.126.net%2Frsc%2Fcss%2Fursweb%2F&cf=ursiframe.css%3F029&MGID=1559565960464.6675&wdaId=&pkid=YlfTAjw&product=lofter
::ffff:192.168.50.200:7884 transfer to 59.56.30.206:80 request block. line=322 url=http://urswebzj.nosdn.127.net/webzj_cdn101/pp_index_dl_442bcee2ddae61b7bab3bba8a8b1dc9b.js
::ffff:192.168.50.200:7907 transfer to 223.252.195.133:80 request block. line=9245 url=http://analytics.163.com/ntes.js
::ffff:192.168.50.200:7967 transfer to 59.111.239.53:80 request super direct. line=50 url=http://passport2.www.lofter.com/webzj/v1.0.1/pub/index_dl2_new.html?cd=%2F%2Fl.bst.126.net%2Frsc%2Fcss%2Fursweb%2F&cf=ursiframe.css%3F029&MGID=1559565960464.6675&wdaId=&pkid=YlfTAjw&product=lofter
::ffff:192.168.50.200:7970 transfer to 59.56.30.206:80 request block. line=322 url=http://urswebzj.nosdn.127.net/webzj_cdn101/pp_index_dl_442bcee2ddae61b7bab3bba8a8b1dc9b.js
::ffff:192.168.50.200:8038 transfer to 59.111.239.60:80 request super direct. line=50 url=http://www.lofter.com/login?urschecked=true
::ffff:192.168.50.200:8040 transfer to 59.56.30.206:80 request block. line=322 url=http://urswebzj.nosdn.127.net/webzj_cdn101/pp_index_dl_442bcee2ddae61b7bab3bba8a8b1dc9b.js
::ffff:192.168.50.200:8054 transfer to 223.252.195.133:80 request block. line=9245 url=http://analytics.163.com/ntes.js
::ffff:192.168.50.200:8093 transfer to 59.56.30.206:80 request block. line=322 url=http://urswebzj.nosdn.127.net/webzj_cdn101/pp_index_dl_442bcee2ddae61b7bab3bba8a8b1dc9b.js
::ffff:192.168.50.200:8101 transfer to 216.58.195.78:443 request block. line=838 url=https://www.google-analytics.com/collect

**Comment by user1121114685** [comment]
请在自定义规则中加入如下
`@@http://urswebzj.nosdn.127.net`
`@@http://analytics.163.com`
---
如果不行的话请再反馈

**Comment by zhouqiubin** [comment]
> ## 请在自定义规则中加入如下
> `@@http://urswebzj.nosdn.127.net`
> `@@http://analytics.163.com`
> 如果不行的话请再反馈

添加后可以正常显示
