### ISSUE TITLE
正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏

### ISSUE THREAD

**Issue by jiaoxiaojia** [user1121114685/koolproxyR#38]
**你所使用的设备：例如 电脑 MAC IPHONE 小米MIX IPHONE8**
我正在使用：

**是否启用http/https模式**
https是否启用:

**证书是否安装正确**
PC安装到【受信任的根证书发布机构】.
安卓7.0以上将.0根证书复制到【/system/etc/security/cacerts】【/system/etc/security/cacerts_google】.
iphone 在设置---通用----关于手机里面信任证书.
MAC 在 【钥匙串访问】中信任。

**是否采取下列措施**
1,重启LEDE
2,重新安装证书

**如果重复以上步骤仍然有问题:**
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

**Comment by user1121114685** [comment]
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

**Comment by jiaoxiaojia** [comment]
17173的明天可以提供，今天已经重新加载了，可以正常访问17173，手机端的淘宝 天猫 网易游戏（猫和老鼠）ios不知道怎么测试，




------------------ 原始邮件 ------------------
发件人: "联盟少侠"<notifications@github.com>; 
发送时间: 2019年6月7日(星期五) 下午4:07
收件人: "user1121114685/koolproxyR"<koolproxyR@noreply.github.com>; 
抄送: "JiaoXiaoJia"<jiaozhenjia@vip.qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [user1121114685/koolproxyR] 正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏 (#38)




请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。

**Comment by user1121114685** [comment]
事实上，你的证书应该是没有安装正确
iphone 在设置---通用----关于手机里面信任证书.

请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。

就可以了。。

**Comment by jiaoxiaojia** [comment]
17173更新最新规则后已经正常，都是网易游戏（猫和老鼠）关闭主规则才能进去，手机ios淘宝 天猫开了https后促销的链接打不卡，要单选http才能正常访问




------------------ 原始邮件 ------------------
发件人: "联盟少侠"<notifications@github.com>; 
发送时间: 2019年6月8日(星期六) 晚上7:57
收件人: "user1121114685/koolproxyR"<koolproxyR@noreply.github.com>; 
抄送: "JiaoXiaoJia"<jiaozhenjia@vip.qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [user1121114685/koolproxyR] 正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏 (#38)




Closed #38.
 
&mdash;

**Comment by user1121114685** [comment]
1 我觉得你证书没装对，但是你也没反馈其它问题。
2 你没有提供日志，虽然你积极回复。但你没有提供重要的东西。我也不能无中生有。请理解。

**Comment by jiaoxiaojia** [comment]
今天更新到2.17 淘宝和网易游戏都可以正常进入了




------------------ 原始邮件 ------------------
发件人: "联盟少侠"<notifications@github.com>;
发送时间: 2019年6月8日(星期六) 晚上8:48
收件人: "user1121114685/koolproxyR"<koolproxyR@noreply.github.com>;
抄送: "JiaoXiaoJia"<jiaozhenjia@vip.qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [user1121114685/koolproxyR] 正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏 (#38)




1 我觉得你证书没装对，但是你也没反馈其它问题。
 2 你没有提供日志，虽然你积极回复。但你没有提供重要的东西。我也不能无中生有。请理解。

**Comment by jiaoxiaojia** [comment]
开了AD调试网页可以打开，下面是开了AD调试后打开17173的日志，图片是没有开前的，
【2019年06月28日 17:39:20】: 关闭koolproxyR主进程...
【2019年06月28日 17:39:21】: koolproxyR主进程已关闭...
【2019年06月28日 17:39:21】: kpr   debug-ad模式启动
koolproxy v3.8.4
listen port=3000
log level=2
thread count=4
work path=/
program path=/koolshare/koolproxyR/koolproxy
data path=/koolshare/koolproxyR/data
ttl mode=188
ttl port=3001
mark mode=0
max fd=131070
init adblock engine
load normal rule: /koolshare/koolproxyR/data/rules/easylistchina.txt
load normal rule: /koolshare/koolproxyR/data/rules/yhosts.txt
load normal rule: /koolshare/koolproxyR/data/rules/user.txt
load secret rule: /koolshare/koolproxyR/data/rules/kp.dat
init https engine
init proxy engine
listen socket on [::]:3000 success
listen socket on [::]:3001 success
::ffff:10.0.0.226:2613 transfer to 117.27.230.186:443 request block. line=2101 url=https://ue.17173cdn.com/a/www/index/2016v2/js/seed.js?201612121806
::ffff:10.0.0.226:2630 transfer to 117.27.230.123:443 request block. line=2895 url=https://log1.17173.com/ping.gif?1561716899557795?t?=?t?=0?t?=0?t?=0?t?=www.17173.com?t?=?t?=?t?=Chrome:77.0.3833.0?t?=0?t?=-1?t?=Win%2010?t?=2560x1440?t?=24-bit?t?=zh-cn?t?=1?t?=0?t?=ch?t?=0?t?=?t?=156129108134533115617166346621851561714767539?t?=1?t?=8?t?=1?t?=0?t?=1?t?=?t?=?t?=
::ffff:10.0.0.226:2631 transfer to 117.27.230.123:443 request block. line=2895 url=https://log1.17173.com/pv?appkey=301&click=g_2_adLink4_tg_no&us=&svn=1&t=1561716899557795&nuv=0&ssid=156129108134533115617166346621851561714767539&se=&kw=&rf=0&bwt=Chrome:%2077.0.3833.0&bw=ch&Jav=0&Flu=-1&scr=2560x1440&Clr=24-bit&Os=Win%2010&ck=1&Ln=zh-cn&rft=1&rfd=0&uid=0&r=1561714824749662
::ffff:10.0.0.226:2632 transfer to 117.27.230.123:443 request block. line=2895 url=https://log1.17173.com/pv?appkey=113&ref=0&ssid=156129108134533115617166346621851561714767539&nuv=0&rtype=1&kw=&rfd=0&se=&uid=0&u=https%3A%2F%2Fwww.17173.com%2F&ads=rE3eAv&svn=1&svn2=1&ol=0&r=1561716156458933
::ffff:10.0.0.226:2650 transfer to 117.27.230.123:443 request block. line=2895 url=https://log1.17173.com/pv?appkey=185&ref=0&ssid=156129108134533115617166346621851561714767539&nuv=0&rtype=1&kw=&rfd=0&se=&uid=0&scr=2560x1440&ck=1&bs=ch&ol=0&diff=8&clt=1&time=3450,2406&u=https%3A%2F%2Fwww.17173.com%2F&rp=16&wn=10397&svn=1&r=1561715790009106
::ffff:10.0.0.226:2653 transfer to 117.27.230.123:443 request block. line=2895 url=https://log1.17173.com/pv?appkey=160&ref=0&ssid=156129108134533115617166346621851561714767539&nuv=0&rtype=1&kw=&rfd=0&se=&uid=0&screen=1100x943&ads=2d2ca7eedf739ef4c3800713ec482e1a|18x36,bebfa0d08da2c142b3dba07546ab86dd|410x40,0e55666a4ad822e0e34299df3591d979|995x38,e49a1bf42f39565435d64f9587beaf4b|0x105,3506a5a001628937f98daf4048554ef6|966x154,QBveUf|0x194,RZNRzi|86x194,2uI363|172x194,rIfM32|258x194,2QZ3qu|344x194,22c92ed29e7f3bd0b63d944e1e6e0b8f|920x194,nqUzyq|0x227,f509e6e247395fcaef19a3dabee98802|0x233,iaYbym|0x233,ER3q63|0x262,6FnQfy|447x262,ZzARz2|0x291,7BVb2y|0x320,RbA3Ef|59x349,7v2m2u|59x378,Jvy6Fz|59x407,dfeb9598fbfb97cc6bbcc0aff2c785d6|0x436,bqUZnq|59x436,aiAZVj|59x465,vUvqIb|59x494,944a5ae3483ed5c1e10bbccb7942a279|0x523,FbYnMz|390x699,0a7671e0ce7999c566962459061bfd73|405x737,82a620629919cfeac27acb64052fb125|850x697,c30226e3c2b9b6c2138e722f792d39fa|1780x634&r=1561715662229742
124.115.10.222:80 transfer to ::ffff:10.0.0.226:2732 response







------------------ 原始邮件 ------------------
发件人: "联盟少侠"<notifications@github.com>;
发送时间: 2019年6月8日(星期六) 晚上8:48
收件人: "user1121114685/koolproxyR"<koolproxyR@noreply.github.com>;
抄送: "JiaoXiaoJia"<jiaozhenjia@vip.qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [user1121114685/koolproxyR] 正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏 (#38)




1 我觉得你证书没装对，但是你也没反馈其它问题。
 2 你没有提供日志，虽然你积极回复。但你没有提供重要的东西。我也不能无中生有。请理解。

**Comment by user1121114685** [comment]
因为没有收到完整的答复，请尝试在自定义规则里面加入如下规则，记得反馈
`@@@@|https://log1.17173.com`

**Comment by jiaoxiaojia** [comment]
优酷视频现在全部由广告




------------------ 原始邮件 ------------------
发件人: "联盟少侠"<notifications@github.com>;
发送时间: 2019年6月29日(星期六) 下午2:44
收件人: "user1121114685/koolproxyR"<koolproxyR@noreply.github.com>;
抄送: "JiaoXiaoJia"<jiaozhenjia@vip.qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [user1121114685/koolproxyR] 正在使用pc，17173要重新保存一下才能打开，手机端iOS淘宝链接打不开开http可以，网易手机游戏要关闭主规则才能进入游戏 (#38)




因为没有收到完整的答复，请尝试在自定义规则里面加入如下规则，记得反馈
 @@@@|https://log1.17173.com
