### ISSUE TITLE
lede软路由启用KPR后网易我的世界无法登陆

### ISSUE THREAD

**Issue by zhangdouya** [user1121114685/koolproxyR#40]
**你所使用的设备：例如 电脑 MAC IPHONE 小米MIX IPHONE8**
我正在使用：电脑

**是否启用http/https模式**
https是否启用:启用

**证书是否安装正确**
PC安装到【受信任的根证书发布机构】.
安卓7.0以上将.0根证书复制到【/system/etc/security/cacerts】【/system/etc/security/cacerts_google】.
iphone 在设置---通用----关于手机里面信任证书.
MAC 在 【钥匙串访问】中信任。

**是否采取下列措施**
1,重启LEDE
2,重新安装证书

**如果重复以上步骤仍然有问题:**
请打开 kpr --附加设置--调试模式-AD ，重复出现问题的地方操作。将日志文件全选粘贴到下方。
调试模式-AD截取不到网易我的世界的登陆信息

客户端提示：获取服务器列表失败，请重试，软路由关掉kpr，启动无问题

**Comment by user1121114685** [comment]
问题属于证书没有安装正确。你需将PC安装到【受信任的根证书发布机构】.在测试。如果还不行打开调试模式_info再次提交log
