### ISSUE TITLE
大佬，有bin文件提供吗？用在Linux上

### ISSUE THREAD

**Issue by PHCSJC** [user1121114685/koolproxyR#44]
之前用的kp，现在想转到大佬的kpr，之前的kp是装上软路由上的，也就是Linux的debian 9上，直接下载Linux版的kp的bin文件，然后运行就可以了。
我看大佬这的README都是安装脚本，所以请教下，大佬是否有提供bin文件呢？或者linux系统上有安装教程吗？
thanks！

**Comment by user1121114685** [comment]
二进制文件和kp是一样的。规则不一样 ，kpr提供的功能不一样不一样。所以请不要担心。你可以将规则更新文件移植到现在的kp上就可以了。

**Comment by PHCSJC** [comment]
嗯嗯，明白了，看到了6个规则，再请教下，kp.dat和kpr_video_list.txt有什么不同呢？

**Comment by user1121114685** [comment]
README中有一个文件树你可以了解下

**Comment by PHCSJC** [comment]
规则一直不下载，是什么原因呢？卡在这一直不动，大佬。
koolproxy v3.8.4
listen port=8119
log level=4
thread count=4
work path=/opt/koolproxy2/data/rules
program path=/opt/koolproxy2/koolproxy
data path=/opt/koolproxy2/data
ttl mode=0
ttl port=0
mark mode=0
max fd=131070
init adblock engine
load normal rule: /opt/koolproxy2/data/rules/easylistchina.txt
WARN: load rule failed: /opt/koolproxy2/data/rules/easylistchina.txt
load normal rule: /opt/koolproxy2/data/rules/fanboy-annoyance.txt
WARN: load rule failed: /opt/koolproxy2/data/rules/fanboy-annoyance.txt
load normal rule: /opt/koolproxy2/data/rules/yhosts.txt
WARN: load rule failed: /opt/koolproxy2/data/rules/yhosts.txt
load secret rule: /opt/koolproxy2/data/rules/kp.dat
WARN: load rule failed: /opt/koolproxy2/data/rules/kp.dat
load normal rule: /opt/koolproxy2/data/rules/kpr_video_list.txt
WARN: load rule failed: /opt/koolproxy2/data/rules/kpr_video_list.txt
load normal rule: /opt/koolproxy2/data/rules/user.txt
WARN: load rule failed: /opt/koolproxy2/data/rules/user.txt
init https engine
init proxy engine
listen socket on [0.0.0.0]:8119 success

**Comment by PHCSJC** [comment]
source.list文件已经修改：
1|easylistchina.txt|https://raw.githubusercontent.com/user1121114685/koolproxyR/master/koolproxyR/koolproxyR/data/rules/easylistchina.txt|
1|fanboy-annoyance.txt|https://raw.githubusercontent.com/user1121114685/koolproxyR/master/koolproxyR/koolproxyR/data/rules/fanboy-annoyance.txt|
1|yhosts.txt|https://raw.githubusercontent.com/user1121114685/koolproxyR/master/koolproxyR/koolproxyR/data/rules/yhosts.txt|
1|kp.dat|https://raw.githubusercontent.com/user1121114685/koolproxyR/master/koolproxyR/koolproxyR/data/rules/kp.dat|
1|kpr_video_list.txt|https://raw.githubusercontent.com/user1121114685/koolproxyR/master/koolproxyR/koolproxyR/data/rules/kpr_video_list.txt|
1|user.txt||

**Comment by user1121114685** [comment]
把KoolProxyR_rule_update.sh修改下就好了。你这有点本末倒置。

**Comment by PHCSJC** [comment]
好吧，感谢大神，我现在直接用wget去下载规则，然后重启下kp。
以前kp是可以自动下载规则的，现在不知道为什么不行了。
