### ISSUE TITLE
建议把havege安装包 丢到koolproxyR目录中

### ISSUE THREAD

**Issue by gzsdbb** [user1121114685/koolproxyR#45]
如题  现在丢在/koolshare怎么看都不顺眼，安装完清理掉也行

**Comment by user1121114685** [comment]
没有清理是有原因的。在你升级系统后可以直接重新安装

**Comment by user1121114685** [comment]
再说谁没事就去看哪个文件夹。

**Comment by gzsdbb** [comment]
嗯嗯  只是建议一下放入koolproxyR目录,这样归类明确点, 不会突然发出多了两个东西, 又找不到北,不知道从何而来,
至于有没有人没事 跑去看这个文件夹那就不知道了, 反正我常常进去里边修改东西
不归类也没什么 反正也不太影响

**Comment by user1121114685** [comment]
看多了就习惯了。
