### ISSUE TITLE
关于规则中逗号加波浪号,~的问题，是规则问题还是本身不支持KP

### ISSUE THREAD

**Issue by babylife** [user1121114685/koolproxyR#53]
使用KP调用KPR规则，可以看到easylistchina.txt规则中有逗号出现异常。 
http://ifeng.com,~imall.ifeng.com##a[href*="imall.ifeng."]
比如上面的规则

此外KP.DAT是否不兼容KP?貌似无法识别。 
admin@K3:/jffs/.koolshare/koolproxy# ./koolproxy
koolproxy v3.8.4
listen port=3000
log level=4
thread count=4
work path=/jffs/.koolshare/koolproxy
program path=/jffs/.koolshare/koolproxy/koolproxy
data path=/jffs/.koolshare/koolproxy/data
ttl mode=0
ttl port=0
mark mode=0
max fd=131070
init adblock engine
load normal rule: /jffs/.koolshare/koolproxy/data/rules/koolproxy.txt
load normal rule: /jffs/.koolshare/koolproxy/data/rules/daily.txt
load secret rule: /jffs/.koolshare/koolproxy/data/rules/kp.dat
load normal rule: /jffs/.koolshare/koolproxy/data/rules/user.txt
load normal rule: /jffs/.koolshare/koolproxy/data/rules/easylistchina.txt
rule line=20178 not support ','
rule line=21197 not support ','
rule line=21863 not support ','
rule line=25882 not support ','
rule line=26901 not support ','
rule line=27567 not support ','
load normal rule: /jffs/.koolshare/koolproxy/data/rules/fanboy-annoyance.txt
load normal rule: /jffs/.koolshare/koolproxy/data/rules/yhosts.txt
load normal rule: /jffs/.koolshare/koolproxy/data/rules/kpr_our_rule.txt
load normal rule: /jffs/.koolshare/koolproxy/data/rules/kp2.dat
WARN: load rule failed: /jffs/.koolshare/koolproxy/data/rules/kp2.dat
init https engine
init proxy engine
can not bind socket: Address in use
listen socket on [0.0.0.0]:3000 error
init proxy engine failed
admin@K3:/jffs/.koolshare/koolproxy#

**Comment by user1121114685** [comment]
https不支持。http支持

**Comment by babylife** [comment]
老大。是HTTP的啊

**Comment by babylife** [comment]
http://ifeng.com,~imall.ifeng.com##a[href*="imall.ifeng."]

**Comment by user1121114685** [comment]
不用在意个别不支持的。不影响的
