### ISSUE TITLE
真好，KP就是订阅不了第三方我才不太想用它。没想到有实施的大手子了

### ISSUE THREAD

**Issue by dNEryno** [user1121114685/koolproxyR#6]
赞一个啊。。

**Comment by user1121114685** [comment]
欢迎大佬更新提意见。

**Comment by dNEryno** [comment]
别的论坛抄过来的。广告净化的内置规则。。。这规则插件用好使。。别的用不太灵光。
http://tools.yiclear.com/ChinaList2.0.txt

**Comment by user1121114685** [comment]
我知道这个规则并使用过一段时间。你可以看看现在还是4月2日更新的。

**Comment by dNEryno** [comment]
现在 也没啥 可用的视频规则了。KP的不再更新了~这个虽然快一个月了。不过好在还能过滤。。另外，今天我离线装竟然失败了。。在虚拟机里:(

**Comment by user1121114685** [comment]
使用在线安装吧
