### ISSUE TITLE
openwrt 在线安装问题

### ISSUE THREAD

**Issue by Aes64X** [user1121114685/koolproxyR#7]
Lean 源码编译 openwrt 编译时去掉了adbyby，kool未加入，命令安装提示：
![QQ截图20190430085909](https://user-images.githubusercontent.com/47932152/56935822-3db96400-6b26-11e9-82cc-9ef1bc8e77b6.png)

**Comment by user1121114685** [comment]
不能直接用于lean的固件，因为安装方式不一样。

**Comment by cakter** [comment]
遇到同样的问题，该怎么解决?
