### ISSUE TITLE
大佬能不能把 Openwrt 格式的页面写出来？

### ISSUE THREAD

**Issue by w7yuu** [user1121114685/koolproxyR#9]
大佬能不能把 Openwrt 格式的页面写出来？`Module_koolproxyR.asp` 太难移植到 luci 了。只要页面可以移植，其它就轻松了。

_Originally posted by @w7yuu in https://github.com/user1121114685/koolproxyR/issues/8#issuecomment-488919404_

**Comment by user1121114685** [comment]
事实上只需要移植规则处理shell脚本就行了。其他地方不需要怎么修改。而且交互界面不能先写。你没见过一个程序先有界面再写核心的吧。。。

**Comment by w7yuu** [comment]
核心可以通用，改的地方比较少，但是界面移植工程量就有些大了。

> 而且交互界面不能先写。你没见过一个程序先有界面再写核心的吧。。。

毕竟是 **照葫芦画瓢** ，界面相同应该没问题吧。（PS：koolproxy 的官方界面辣鸡的一批，kpr 的好上很多）

**Comment by user1121114685** [comment]
你可以只改核心规则。不用改界面。这样就好了。
